{
  "text-color": "#bcbec4",
  "background-color": "#1e1f22",
  "line-number-color": "#4b5059",
  "line-number-background-color": "#1e1f22",
  "text-styles": {
    "Alert": {
      "text-color": "#f2c55c",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Annotation": {
      "text-color": "#67a37c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": true
    },
    "Attribute": {
      "text-color": "#bcbec4",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BaseN": {
      "text-color": "#2aacb8",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BuiltIn": {
      "text-color": "#56a8f5",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Char": {
      "text-color": "#6aab73",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Comment": {
      "text-color": "#7a7e85",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Constant": {
      "text-color": "#c77dbb",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "ControlFlow": {
      "text-color": "#cf8e6d",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DataType": {
      "text-color": "#16baac",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DecVal": {
      "text-color": "#2aacb8",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Documentation": {
      "text-color": "#5f826b",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Error": {
      "text-color": "#f75464",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Extension": {
      "text-color": "#b3ae60",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Float": {
      "text-color": "#2aacb8",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Function": {
      "text-color": "#56a8f5",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Import": {
      "text-color": "#cf8e6d",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Information": {
      "text-color": "#56a8f5",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Keyword": {
      "text-color": "#cf8e6d",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Operator": {
      "text-color": "#bcbec4",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Preprocessor": {
      "text-color": "#b3ae60",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialChar": {
      "text-color": "#cf8e6d",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialString": {
      "text-color": "#6aab73",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "String": {
      "text-color": "#6aab73",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Variable": {
      "text-color": "#bcbec4",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "VerbatimString": {
      "text-color": "#6aab73",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Warning": {
      "text-color": "#f2c55c",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    }
  }
}